# Docker Compose est un outil écrit en Python qui permet de décrire, dans un fichier YAML, plusieurs conteneurs comme un ensemble de services.

version: '3.7'

# services: keyword indicates that the following lines will define a list of services (containers) to run.
services:
  nginx: 
    container_name: nginx 
    hostname: nginx
    # depends_on: specifies that this service depends on the mariadb service, which means that the mariadb service will be started before the nginx service.
    depends_on:
      - mariadb
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception-network
    # ports: specifies that the container will publish port 443 to the host.
    ports: 
      - "443:443"
    # volumes: specifies that the wordpress_v volume will be mounted to the /var/www/html directory inside the container.
    volumes: 
      - wordpress_v:/var/www/html
    env_file: .env

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception-network
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file: .env
      
  wordpress:
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
       - wordpress_v:/var/www/html
    restart: on-failure
    networks:
      - inception-network
    env_file: .env


volumes:
  wordpress_v:
    driver: local  # driver:local means that the volume is stored on the host machine
    driver_opts:
      type: none   # type: none option specifies that the volume is not created from a pre-existing volume or image
      o: bind
      device: ${DATA_FOLDER}/wordpress
       
  mariadb_v:
     driver: local 
     driver_opts:
       type: none
       o: bind
       device: ${DATA_FOLDER}/mariadb

networks:
  inception-network: