# Docker Compose est un outil écrit en Python qui permet de décrire, dans un fichier YAML, plusieurs conteneurs comme un ensemble de services. 

version: '3'
#L'ensemble des conteneurs qui doivent être créés doivent être définis sous l'argument services  . Chaque conteneur commence avec un nom qui lui est propre ; dans notre cas, notre premier conteneur se nommera db  .
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: "mysql -u${DB_USER} -p${DB_USER_PASSWORD} ${DB_NAME} -e 'SELECT 1'"
      interval : 1s
      retries: 10
    
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volume:
      - wordpress_v:/var/www/wordpress
    depends_on:
      - mariadb:
        condition: service-healthy
    restart: unless-stopped
  
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_v:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    restart: unless-stopped

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ccalas/data/mariadb

  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ccalas/data/wordpress