# MariaDB
# Une base de donnees relationnelle open source

FROM debian:buster

RUN sudo apt update -yq 
	&& sudo apt-get upgrade -yq
	&& apt-get install mariadb-server -yq

EXPOSE 3306

LABEL version="1.0"
LABEL description="MariaDB Server"

HEALTHCHECK --start-period=5m \
CMD mariadb -e 'SELECT @@datadir;' || exit 1

CMD ["mysqld"]