# # NGINX - SERVER
# # nginx is an HTTP and reverse proxy server, a mail proxy server and a mail proxy server, and a generic TCP/UDP proxy server

# FROM debian:buster

# RUN apt update -yq \
# 	&& apt-get upgrade -yq \
# 	&& apt install nginx -yq


# #generate certificate with openSSL
# RUN mkdir -p /etc/nginx/ssl \
# 	&& apt-get install openssl -yq \
# 	&& chmod 755 /etc/nginx/ssl

# #req : we want to use tge tool for creating a certificate signing request (CSR) or  self signed X.509 certificate

# #new: This option is used to create a new CSR or self-signed certificate.

# #nodes: This option tells OpenSSL not to encrypt the private key that is generated. This means that the private key will not be protected by a passphrase and anyone with access to the key file will be able to read it.

# #x509: This option specifies that we want to create a self-signed X.509 certificate rather than a certificate signing request (CSR).

# #newkey rsa:2048: This option generates a new RSA key pair with a key size of 2048 bits. The private key is not encrypted, as specified by the -nodes option.

# #out /etc/nginx/ssd/42_inception.crt: This option specifies the output file where the generated certificate will be saved. In this case, the file is /etc/nginx/ssd/42_inception.crt

# #keyout /etc/: This option specifies the output file where the generated private key will be saved. 

# #subj argument is used to specify the subject information for the certificate, including various fields such as country name, state or province name, locality name, organization name, organizational unit name, common name, and other fields that can be included depending on the certificate's purpose.
# RUN openssl req\
# 			-new\
# 			-nodes\
# 			-x509\
# 			-newkey rsa:2048\
# 			-out /etc/nginx/ssl/42_inception.crt\
# 			-keyout /etc/nginx/ssl/42_inception.key\
# 			-subj "/C=FR/ST=IDF/L=Paris/O=42/OU=School42/CN=ccalas.42.fr/UID=ccalas"


# RUN	chmod 755 /var/www/html \
#     && chown -R www-data:www-data /var/www/html

# EXPOSE 443

# COPY conf/nginx.conf /etc/nginx/nginx.conf

# #the daemon off; directive tells Nginx to stay in the foreground. For containers this is useful as best practice is for one container = one process. One server (container) has only one service.
# CMD ["nginx",  "-g",  "daemon off;"]



#image built from...
FROM debian:buster

#update cash and install ngnix with the status check after
RUN apt-get update && apt-get upgrade -y
RUN apt-get install nginx -y

#install openssl and generating a self certificate
RUN mkdir -p /etc/nginx/ssl
RUN apt-get install openssl -y
RUN openssl req\
	-new\
	-nodes\
	-x509\ 
	-newkey	rsa:2048\ 
	-out /etc/nginx/ssl/inception.crt\ 
	-keyout /etc/nginx/ssl/inception.key\ 
	-subj "/C=FR/ST=IDF/L=Paris/O=42/OU=Shool 42/CN=masamoil.42.fr/UID=masamoil"

RUN mkdir -p /var/www/html
#RUN mkdir -p /var/run/nginx

COPY conf/nginx.conf /etc/nginx/conf.d/nginx.conf

RUN chmod -R 755 /var/www/html 
RUN chown -R www-data:www-data /var/www/html

#open the port 443
#EXPOSE 443

ENTRYPOINT ["nginx", "-g", "daemon off;" ]